name: Run Pytests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: tests
          environment-file: environment.yml
          cache-environment: true
          cache-environment-key: "env-${{ hashFiles('environment.yml') }}"
          create-args: >-
            python=3.12

      - name: Run pytest
        shell: bash -l {0}
        run: pytest -v
